---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-redis-tester
  namespace: gloo-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-tester
  template:
    metadata:
      labels:
        app: redis-tester
    spec:
      containers: 
      - name: redis
        image: kodacd/aws-elasticache-redis-tester:latest
        imagePullPolicy: Always
        env:
        - name:  LOG_LEVEL
          value:  debug  
        - name:  PORT
          value:  "8080"   
        - name:  REDIS_HOST
          valueFrom:
            secretKeyRef:
              name:  redis-config
              key:  host 
        - name:  REDIS_PORT
          valueFrom:
            secretKeyRef:
              name:  redis-config
              key:  port
              optional: true
        - name:  REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  redis-config
              key:  token
        # convenience for redis-cli client
        - name:  REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              name:  redis-config
              key:  token
        - name: REDIS_TEST_KEY_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort:  8080
          name:  http
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2