---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: default
  namespace: gloo-mesh
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: default
      namespace: gloo-mesh
  http:
    - name: sanity
      matchers:
        - uri:
            prefix: /sanity
      labels:
        route: sanity
      directResponse:
        status: 200
        body: "it's alive"
    - name: vd-demo
      matchers:
      - uri:
          prefix: /vd-demo
      forwardTo:
        pathRewrite: /
        destinations:
          - ref:
              name: demo
            kind: VIRTUAL_DESTINATION
            port:
              number: 8080
    - name: svc-demo
      matchers:
        - uri:
            prefix: /svc-demo
      labels:
        route: demo
      forwardTo:
        pathRewrite: /
        destinations:
        - ref:
            name: demo
            namespace: demo
          port:
            number: 8080
          kind: SERVICE