
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-aws-lb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: "1.4.5"
    chart: aws-load-balancer-controller
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        replicaCount: 1
        clusterName: ha-demo-workload-1
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::931713665590:role/ha-demo-workload-1-aws-lb-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  destination:
    server: https://7C64B9DF9D91D7DD4F130D8C8AEC90D6.gr7.us-east-1.eks.amazonaws.com
    namespace: kube-system  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-ext-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: "0.7.2"
    chart: external-secrets
    helm:
      releaseName: external-secrets
      values: |
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::931713665590:role/ha-demo-workload-1-ext-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  destination:
    server: https://7C64B9DF9D91D7DD4F130D8C8AEC90D6.gr7.us-east-1.eks.amazonaws.com
    namespace: kube-system  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  destination:
    server: https://7C64B9DF9D91D7DD4F130D8C8AEC90D6.gr7.us-east-1.eks.amazonaws.com
    namespace: kube-system  