---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-gloo-platform-crds
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    name: workload-1
  project: default
  source:
    chart: gloo-platform-crds
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts #https://storage.googleapis.com/gloo-platform-dev/platform-charts/helm-charts
    targetRevision: v2.4.0-rc1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-gloo-platform
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    name: workload-1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    chart: gloo-platform
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts #https://storage.googleapis.com/gloo-platform-dev/platform-charts/helm-charts
    targetRevision: v2.4.0-rc1
    helm:
      values: |
        common:
          cluster: eks-cluster-us-east-1
        # ISSUE: demo must be set to create gloo-mesh-addons
        demo:
          manageAddonNamespace: true

        glooAgent:
          enabled: true
          relay:
            serverAddress: "mgmt.ha-demo.vpc:9900"
            clientTlsSecret:
              name: gloo-mesh-agent-eks-cluster-us-east-1-tls-cert
            tokenSecret:
              key: null
              name: null
              namespace: null

        glooUi:
          enabled: false

        glooMgmtServer:
          enabled: false

        extAuthService:
          enabled: false

        legacyMetricsPipeline:
          enabled: false

        telemetryGateway:
          enabled: false
          service:
            type: ClusterIP

        telemetryCollector:
          enabled: true
          config:
            exporters:
              otlp: 
                endpoint: otel.ha-demo.vpc:4317

        prometheus:
          enabled: false

        redis:
          deployment:
            enabled: false
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-tls
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    name: workload-1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/ha-demo/workload-1/tls
    directory:
      recurse: true