---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-httpbin
  namespace: argocd
  labels:
    solo.io/demo: httpbin
spec:
  destination:
    namespace: kube-system
    name: workload-1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/ha-demo/workload-demo
    targetRevision: main
    directory:
      recurse: true
