--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-1-promstack
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - Replace=true
    - ServerSideApply=true
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: v48.2.2
    helm:
      releaseName: prom
      values: |
        grafana:
          additionalDataSources:
          - name: prometheus-gloo-platform
            type: prometheus
            url: http://prometheus-server.gloo-mesh:80