---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-1-demo
  namespace: argocd
  labels:
    solo.io/demo: httpbin
spec:
  destination:
    namespace: gloo-mesh
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/mgmt-demo
    targetRevision: main
    directory:
      recurse: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-2-demo
  namespace: argocd
  labels:
    solo.io/demo: httpbin
spec:
  destination:
    namespace: gloo-mesh
    name: mgmt-2
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/mgmt-demo
    targetRevision: main
    directory:
      recurse: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-1-httpbin
  namespace: argocd
  labels:
    solo.io/demo: httpbin
spec:
  destination:
    namespace: httpbin
    name: workload-1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/workload-demo
    targetRevision: main
    directory:
      recurse: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-2-httpbin
  namespace: argocd
  labels:
    solo.io/demo: httpbin
spec:
  destination:
    namespace: httpbin
    name: workload-2
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/workload-demo
    targetRevision: main
    directory:
      recurse: true
