--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-1-external-dns
  namespace: argocd
  labels:
    solo.io/infra: external-dns
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  source:
    repoURL: https://github.com/bensolo-io/multi-region-demo.git
    path: argocd/ha-demo/mgmt-1/external-dns
    targetRevision: main
    directory:
      recurse: true
