apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.9/manifests/install.yaml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-okta.yaml
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
    path: argocd-rbac.yaml
patchesJson6902:
  - target:
      kind: ServiceAccount
      name: argocd-application-controller
      version: v1
    patch: |
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: ${ argocd-controller-arn }
  - target:
      kind: ServiceAccount
      name: argocd-applicationset-controller
      version: v1
    patch: |
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: ${ argocd-controller-arn }
  - target:
      kind: ServiceAccount
      name: argocd-server
      version: v1
    patch: |
      - op: add
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: ${ argocd-controller-arn }
  - target:
      kind: Deployment
      name: argocd-server
      version: v1
    patch: |
      - op: add
        path: /spec/template/spec/securityContext
        value: { "fsGroup": 999 }
  - target:
      kind: Deployment
      name: argocd-applicationset-controller
      version: v1
    patch: |
      - op: add
        path: /spec/template/spec/securityContext
        value: { "fsGroup": 999 }
  - target:
      kind: StatefulSet
      name: argocd-application-controller
      version: v1
    patch: |
      - op: add
        path: /spec/template/spec/securityContext
        value: { "fsGroup": 999 }