apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://localhost:8383
  caData: ==
  dex.config: |
    logger:
      level: debug
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: https://****
        caData: ==
        redirectURI: https://localhost:8383/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group