apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: istio-eastwestgateway
  namespace: gloo-mesh
spec:
  installations:
  # The revision for this installation, such as 1-17-3
  - gatewayRevision: 1-17-2
    # List all workload clusters to install Istio into
    clusters:
    - name: workload-1
      # If set to true, the spec for this revision is applied in the cluster
      activeGateway: true
    - name: workload-2
      activeGateway: true
    istioOperatorSpec:
      # No control plane components are installed
      profile: empty
      # Solo.io Istio distribution repository; required for Gloo Istio.
      # You get the repo key from your Solo Account Representative.
      hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
      # Any Solo.io Gloo Istio tag
      tag: 1.17.2-solo
      components:
        ingressGateways:
        # Enable the default east-west gateway
        - name: istio-eastwestgateway
          # Deployed to gloo-mesh-gateways by default
          namespace: gloo-mesh-gateways
          enabled: true
          label:
            # Set a unique label for the gateway. This is required to
            # ensure Gateways can select this workload.
            istio: eastwestgateway
            app: istio-eastwestgateway
          k8s:
            env:
              # 'sni-dnat' enables AUTO_PASSTHROUGH mode for east-west communication through the gateway.
              # The default value ('standard') does not set up a passthrough cluster.
              # Required for multi-cluster communication and to preserve SNI.
              - name: ISTIO_META_ROUTER_MODE
                value: "sni-dnat"
            serviceAnnotations:
              external-dns.alpha.kubernetes.io/alias: "true"
              service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-scheme: internal
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: TCP
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            service:
              type: LoadBalancer
              selector:
                istio: eastwestgateway
              # Default ports
              ports:
                # Port for health checks on path /healthz/ready.
                # For AWS ELBs, this port must be listed first.
                - name: status-port
                  port: 15021
                  targetPort: 15021
                # Port for multicluster mTLS passthrough
                # Gloo looks for this default name 'tls' on a gateway
                # Required for Gloo east/west routing
                - name: tls
                  port: 15443
                  targetPort: 15443
                    