---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: default
  namespace: gloo-mesh
spec:
  hosts:
    - 'api.ha-demo.vpc'
  virtualGateways:
    - name: default
      namespace: gloo-mesh
  http:
    - name: sanity
      matchers:
        - uri:
            prefix: /sanity
      labels:
        route: sanity
      directResponse:
        status: 200
        body: "it's alive"
    - name: demo
      matchers:
      - uri:
          prefix: /demo
      forwardTo:
        pathRewrite: /
        destinations:
          - ref:
              name: httpbin
            kind: VIRTUAL_DESTINATION
            port:
              number: 80

