---
apiVersion: admin.gloo.solo.io/v2
kind: KubernetesCluster
metadata:
  name: workload-1
  namespace: gloo-mesh
spec:
  clusterDomain: cluster.local
---
apiVersion: admin.gloo.solo.io/v2
kind: KubernetesCluster
metadata:
  name: workload-2
  namespace: gloo-mesh
spec:
  clusterDomain: cluster.local
